image: node

before_script:
  - npm install

cache:
  paths:
    - node_modules/

pages:
  variables:
    BASE_PATH: "/zakupki/"
  script:
    - npm run generate
    - cp public/index.html public/404.html
  artifacts:
    paths:
      - public
  only:
    - master
