version: '3'

services:
  zakupki:
    build:
      context: .
    command: ['npm', 'run', 'dev']
    volumes:
      - ./assets:/src/assets
      - ./components:/src/components
      - ./layouts:/src/layouts
      - ./middleware:/src/middleware
      - ./pages:/src/pages
      - ./plugins:/src/plugins
      - ./static:/src/static
      - ./store:/src/store
      - ./.eslintrc.js:/src/.eslintrc.js
      - ./nuxt.config.js:/src/nuxt.config.js
    environment:
      - API_URL
    env_file:
      - .env
    ports:
      - 3000:80

  centrala:
    image: macieklewkowicz/centrala
    environment:
      - GROCY_API_URL_ANONYMOUS=https://demo.grocy.info/api/
      - GROCY_API_URL=http://grocy/api/
    ports:
      - 9080:80
  grocy:
    image: linuxserver/grocy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Warsaw
    ports:
      - 9081:80
    volumes:
      - grocy_config:/config

volumes:
  grocy_config:
